### ISSUE TITLE
[Feature request] user authentication

### ISSUE THREAD

**Issue by abstractionmage** [Fourdee/DietPi-Dashboard#2]
At the moment it is quite easy for anyone on my home network to get full control over my DietPi installation using Dietpi-Dashboard, as there doesn't seem to be any user authentication in place yet. All they have to do is find out is the IP address of my Raspberry Pi and which port Dietpi-Dashboard is running on, open that up in a web browser, navigate to the terminal view and they now have access to a root shell without ever having to type in a password. Yup, the terminal in Dietpi-Dashboard automatically logs itself in as root even though I have the local-terminal option in diepti-autostart set to "Manual login".
I would really feel a lot safer using this application if it had proper, hard-to-circumvent user authentication in place (like portainer or most other security-critical web applications)

**Comment by nonnorm** [comment]
Hi,
Please leave all feature requests and issues at https://github.com/ravenclaw900/dietpi-dashboard, not this repository. The terminal should be considered more like an SSH session, not a local console, as it starts the shell with root permissions. Password protection was implemented with v0.3.2, actually before you posted this, so please update.

**Comment by abstractionmage** [comment]
Thanks, password protection works now after updating to the most recent version.
Sorry for the inconvenience.
